can_province_abbrev = {
  'Alberta': 'AB',
  'British Columbia': 'BC',
  'Manitoba': 'MB',
  'New Brunswick': 'NB',
  'Newfoundland and Labrador': 'NL',
  'Northwest Territories': 'NT',
  'Nova Scotia': 'NS',
  'Nunavut': 'NU',
  'Ontario': 'ON',
  'Prince Edward Island': 'PE',
  'Quebec': 'QC',
  'Saskatchewan': 'SK',
  'Yukon': 'YT',
}

can_province_names = {
  'AB': 'Alberta',
  'BC': 'British Columbia',
  'MB': 'Manitoba',
  'NB': 'New Brunswick',
  'NL': 'Newfoundland and Labrador',
  'NS': 'Nova Scotia',
  'NT': 'Northwest Territories',
  'NU': 'Nunavut',
  'ON': 'Ontario',
  'PE': 'Prince Edward Island',
  'QC': 'Quebec',
  'SK': 'Saskatchewan',
  'YT': 'Yukon'
}

non_iso_3166_country_names = {
  'russia': 'Russian Federation',
  'uk/england': 'England',
  'uk': 'England',
  'uk/endland': 'England',
  'united kingdom': 'England',
  'uk/scotland': 'Scotland',
  'uk/wales': 'Wales',
  'uk/north wales': 'Wales', 
  'uae': 'United Arab Emirates',
  'uar': 'United Arab Emirates',
  'u.a.r.': 'United Arab Emirates',
  'united arab republic': 'United Arab Emirates',
  'czech republic': 'Czech Republic',
  'macedonia': 'Macedonia',
  'méxico': 'Mexico',
  'northern cyprus': 'Northern Cyprus',
  'iran': 'Iran',
  'costa rca': 'Costa Rica',
  'republic of panama': 'Republic of Panama',
  'panama': 'Republic of Panama',
  'usvi': 'Virgin Islands of the United States',
  'u. s. virgin islands': 'Virgin Islands of the United States',
  'rep. of ireland': 'Ireland',
  'republic of ireland': 'Ireland',
  'grand cayman island': 'Cayman Islands',
  'grand canary island': 'Spain',
  'tenerife': 'Spain', 
  'reunion island': 'Réunion',
  'northern ireland': 'Northern Ireland',
  'british virgin islands': 'Virgin Islands',
  'northern marianas': 'Northern Mariana Islands',
  'western australia': 'Australia',
  'south australia': 'Australia',
  'bosnia/herzogovina': 'Bosnia and Herzegovina',
  'bosnia-herzegovina': 'Bosnia and Herzegovina',
  'bosnia': 'Bosnia and Herzegovina',
  'boxnia': 'Bosnia and Herzegovina',
  'trinidad/tobago': 'Trinidad and Tobago',
  'trinidad': 'Trinidad and Tobago',
  'cape verde islands': 'Cabo Verde',
  'south korea': 'Republic of Korea',
  'venezuela': 'Venezuela',
  'syria': 'Syria',
  'brasil': 'Brazil',
  'west germany': 'Germany',
  'w. germany': 'Germany',
  'vietnam': 'Viet Nam',
  'vie tnam': 'Viet Nam',
  'brunei': 'Brunei Darussalam',
  'bolivia': 'Bolivia',
  'st. kitts': 'Saint Kitts and Nevis',
  'puertorico': 'Puerto Rico',
  'guatamala': 'Guatamala',
  'iraq': 'Iraq', 
  'indonesia': 'Indonesia',
  
}